//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNLFish.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loai_ca
    {
        public loai_ca()
        {
            this.CHITIETDONTHANGs = new HashSet<CHITIETDONTHANG>();
        }
    
        public int id { get; set; }
        public string MaCa { get; set; }
        public string fish_name { get; set; }
        public string Image { get; set; }
        public string Color { get; set; }
        public string Description { get; set; }
        public string NguonGoc { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual ICollection<CHITIETDONTHANG> CHITIETDONTHANGs { get; set; }
        public virtual dong_ca dong_ca { get; set; }
    }
}
