//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNLFish.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dong_ca
    {
        public dong_ca()
        {
            this.loai_ca = new HashSet<loai_ca>();
        }
    
        public string MaCa { get; set; }
        public string TenDongCa { get; set; }
    
        public virtual ICollection<loai_ca> loai_ca { get; set; }
    }
}
